import { fetchFile } from "@ffmpeg/util";
import { getFFmpeg, ffmpegWasmAvailable } from "@/lib/ffmpeg-stitch";

/**
 * format-engine — Stage 8 of the pipeline.
 *
 * Takes the finished (optionally branded) reel and packages it per platform.
 * This is deterministic FFmpeg work, not regeneration — the machine already
 * produced the footage; format selection is only packaging.
 *
 *   instagram : 9:16, ≤30s, 30fps, faststart          — Reels
 *   tiktok    : 9:16, ≤60s, 30fps, loudness-normalised — TikTok/Shorts
 *   mls       : 16:9 letterboxed, ≤30s, AI-disclosure metadata — MLS upload
 *
 * FAIL-SAFE: returns null on any problem so the caller ships the master file.
 */

export type ExportFormat = "instagram" | "tiktok" | "mls";

const SPEC: Record<ExportFormat, { maxSeconds: number; vf: string; label: string }> = {
  instagram: {
    maxSeconds: 30,
    vf: "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30",
    label: "Instagram Reel",
  },
  tiktok: {
    maxSeconds: 60,
    vf: "scale=1080:1920:force_original_aspect_ratio=decrease,pad=1080:1920:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30",
    label: "TikTok",
  },
  mls: {
    // MLS systems overwhelmingly want landscape; letterbox rather than crop so
    // nothing in the property frame is lost.
    maxSeconds: 30,
    vf: "scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=30",
    label: "MLS Export",
  },
};

export async function packageForFormat(opts: {
  /** Source video: a URL (master) or an already-branded Blob. */
  source: string | Blob;
  format: ExportFormat;
  /** Shown in file metadata + MLS disclosure. */
  title?: string;
  onProgress?: (msg: string) => void;
}): Promise<Blob | null> {
  const { source, format, title, onProgress } = opts;
  try {
    if (!ffmpegWasmAvailable().ok) return null;
    const spec = SPEC[format];

    onProgress?.(`Packaging for ${spec.label}…`);
    const ff = await getFFmpeg((m) => onProgress?.(m));

    const input = source instanceof Blob
      ? new Uint8Array(await source.arrayBuffer())
      : await fetchFile(source);
    await ff.writeFile("src.mp4", input);

    const args = [
      "-i", "src.mp4",
      "-t", String(spec.maxSeconds),
      "-vf", spec.vf,
      "-c:v", "libx264", "-preset", "veryfast", "-crf", "23",
      "-pix_fmt", "yuv420p", "-movflags", "+faststart",
      "-c:a", "aac", "-b:a", "128k",
      // Metadata — the MLS export carries the AI-disclosure tag inline, which
      // is what keeps it compliant on upload.
      "-metadata", `title=${title || "The Vantage listing reel"}`,
      "-metadata", "comment=AI-enhanced listing media generated by The Vantage. Property features derived from supplied listing photos.",
    ];
    if (format === "mls") {
      args.push("-metadata", "description=AI-GENERATED / AI-ENHANCED VISUAL MEDIA — disclosure per MLS policy.");
    }
    args.push("out.mp4");

    await ff.exec(args);
    const data = (await ff.readFile("out.mp4")) as Uint8Array;
    if (!data || data.byteLength < 1000) return null;
    return new Blob([data.slice().buffer as ArrayBuffer], { type: "video/mp4" });
  } catch (e) {
    console.warn("[format-engine] falling back to master file:", e);
    return null;
  }
}
