/**
 * Real customer-grade samples generated by The Vantage.
 * Used across landing pages, sliders, and case studies as proof-of-quality.
 *
 * Files live in /public/vantage/ — the paths below are URL-relative.
 * No imports; just paths the browser can fetch.
 */

export interface VantageSample {
  id: string;
  category: "construction" | "cleanup" | "setup" | "listing_single" | "listing_bundle" | "sketch_to_real";
  label: string;
  byline: string;
  /** Final delivered video — what you put on Reels */
  video: string;
  /** AI-reconstructed "before" state (only for transformations) */
  before?: string;
  /** Original "after" photo the customer uploaded */
  after?: string;
  /** Optional poster frame for video <video poster> */
  poster?: string;
}

export const VANTAGE_SAMPLES: VantageSample[] = [
  {
    id: "ranch-build",
    category: "construction",
    label: "Ranch Build · Full Home",
    byline: "CONSTRUCTION · NORTHEAST",
    video: "/vantage/ranch-build/result.mp4",
    after: "/vantage/ranch-build/input.png",
    poster: "/vantage/ranch-build/input.png",
  },
  {
    id: "backyard-slow-reveal",
    category: "construction",
    label: "Backyard · Slow Reveal",
    byline: "LANDSCAPING · BACKYARD BUILD",
    video: "/vantage/backyard-slow-reveal/result.mp4",
    before: "/vantage/backyard-slow-reveal/before.jpg",
    after: "/vantage/backyard-slow-reveal/input.jpg",
    poster: "/vantage/backyard-slow-reveal/input.jpg",
  },
  {
    id: "ranch-clean",
    category: "cleanup",
    label: "Ranch · Cleanup",
    byline: "RUBBISH REMOVAL · BEFORE-AFTER",
    video: "/vantage/ranch-clean/video.mp4",
    before: "/vantage/ranch-clean/before.webp",
    after: "/vantage/ranch-clean/input.png",
    poster: "/vantage/ranch-clean/input.png",
  },
  {
    id: "setup",
    category: "setup",
    label: "Event Setup · Venue Styling",
    byline: "VENUE STYLED · DRESSED FROM EMPTY",
    video: "/vantage/setup/video.mp4",
    before: "/vantage/setup/before.webp",
    after: "/vantage/setup/after.jpeg",
    poster: "/vantage/setup/after.jpeg",
  },
  {
    id: "sketch",
    category: "sketch_to_real",
    label: "Sketch to Reality",
    byline: "PROPERTY PHOTO · HAND-DRAWN REVEAL",
    video: "/vantage/sketch/result.mp4",
    after: "/vantage/sketch/original.webp",
    poster: "/vantage/sketch/original.webp",
  },
  {
    id: "just-listed",
    category: "listing_single",
    label: "Just Listed · Single Photo Reel",
    byline: "ANIMATE SINGLE · BADGE OVERLAY",
    video: "/vantage/just-listed/video.mp4",
  },
];

/**
 * The 6-photo Listing Bundle sample. Each entry is one source photo + its
 * 5-second cinematic clip. Wire these into a slider to demo the bundle flow.
 */
export const VANTAGE_LISTING_BUNDLE = Array.from({ length: 6 }, (_, i) => ({
  index: i + 1,
  photo: `/vantage/listing-bundle/${i + 1}.webp`,
  clip: `/vantage/listing-bundle/${i + 1}.mp4`,
}));

/** Quick-access lookups */
export const getSampleById = (id: string) => VANTAGE_SAMPLES.find((s) => s.id === id);
export const getSamplesByCategory = (category: VantageSample["category"]) =>
  VANTAGE_SAMPLES.filter((s) => s.category === category);

/** Top three for homepage hero / featured slots */
export const FEATURED_SAMPLES = [
  VANTAGE_SAMPLES.find((s) => s.id === "ranch-build")!,
  VANTAGE_SAMPLES.find((s) => s.id === "backyard-slow-reveal")!,
  VANTAGE_SAMPLES.find((s) => s.id === "ranch-clean")!,
];
