import { useState, useEffect, useRef } from "react";
import { Link } from "react-router-dom";
import { Helmet } from "react-helmet-async";
import { X } from "lucide-react";
import { useIsMobile } from "@/hooks/use-mobile";

interface BeforeInstallPromptEvent extends Event {
  prompt: () => Promise<void>;
  userChoice: Promise<{ outcome: "accepted" | "dismissed" }>;
}

const PhoneMockup = ({ videoSrc, label }: { videoSrc: string; label: string }) => (
  <div className="flex flex-col items-center flex-shrink-0">
    <div
      className="relative overflow-hidden"
      style={{
        width: 240, height: 430, background: "#000",
        border: "8px solid #2A2A2A", borderRadius: 36,
        boxShadow: "0 40px 80px rgba(0,0,0,0.8), inset 0 0 0 1px #333, 0 0 40px rgba(232,197,71,0.06)",
      }}
    >
      <div className="absolute top-0 left-1/2 -translate-x-1/2 z-10" style={{ width: 90, height: 24, background: "#000", borderRadius: "0 0 16px 16px" }} />
      <video src={videoSrc} autoPlay muted loop playsInline className="absolute inset-0 w-full h-full object-cover" />
    </div>
    <p className="font-mono text-[10px] tracking-[2px] mt-3 text-center" style={{ color: "#555" }}>{label}</p>
  </div>
);

const Demo = () => {
  const isMobile = useIsMobile();
  const [deferredPrompt, setDeferredPrompt] = useState<BeforeInstallPromptEvent | null>(null);
  const [showInstallModal, setShowInstallModal] = useState(false);
  const isStandalone = typeof window !== "undefined" && window.matchMedia("(display-mode: standalone)").matches;

  useEffect(() => {
    const handler = (e: Event) => {
      e.preventDefault();
      setDeferredPrompt(e as BeforeInstallPromptEvent);
    };
    window.addEventListener("beforeinstallprompt", handler);
    return () => window.removeEventListener("beforeinstallprompt", handler);
  }, []);

  const handleInstallClick = async () => {
    if (deferredPrompt) {
      await deferredPrompt.prompt();
      setDeferredPrompt(null);
    } else {
      setShowInstallModal(true);
    }
  };

  // Detect iOS
  const isIOS = typeof navigator !== "undefined" && /iPad|iPhone|iPod/.test(navigator.userAgent);

  return (
    <>
      <Helmet>
        <title>See The Vantage In Action — Free Demo</title>
        <meta name="description" content="Watch real transformation videos generated by The Vantage. No editing, no crew — just one after photo each." />
      </Helmet>

      <div style={{ background: "#0A0A0A" }} className="min-h-screen">
        {/* Header */}
        <header className="fixed top-0 left-0 right-0 z-50 flex items-center justify-between px-4" style={{ height: 56, background: "#0A0A0A" }}>
          <Link to="/" className="font-mono text-[14px] font-bold" style={{ color: "#E8C547" }}>THE VANTAGE</Link>
          <Link to="/login?returnUrl=/video?mode=transform" className="font-mono text-[13px]" style={{ color: "#E8C547" }}>Get Started →</Link>
        </header>

        {isMobile ? (
          /* ═══ MOBILE LAYOUT ═══ */
          <>
            {/* Section 1 — Intro */}
            <section className="min-h-screen flex flex-col items-center justify-center px-4 text-center pt-14">
              <div className="flex items-center justify-center mb-4" style={{ width: 80, height: 80, borderRadius: 20, background: "#000", border: "2px solid #E8C547" }}>
                <span className="font-display font-bold text-[44px]" style={{ color: "#E8C547" }}>V</span>
              </div>
              <p className="font-mono text-[12px] font-bold mb-4" style={{ color: "#E8C547" }}>THE VANTAGE</p>
              <h1 className="font-display font-bold text-[48px] leading-[0.9] mb-4" style={{ color: "#fff" }}>
                See what gets made.
              </h1>
              <div className="absolute bottom-8 animate-bounce">
                <span className="text-[24px]" style={{ color: "#555" }}>↓</span>
              </div>
            </section>

            {/* Section 2 — Video 1 */}
            <section className="relative w-full" style={{ height: "100vh" }}>
              <video src="/videos/transform-1.mp4" autoPlay muted loop playsInline className="absolute inset-0 w-full h-full object-cover" />
              <div className="absolute inset-0" style={{ background: "linear-gradient(to top, rgba(0,0,0,0.9) 0%, transparent 60%)" }} />
              <div className="absolute bottom-0 left-0 right-0 p-6 pb-10">
                <h2 className="font-display font-bold text-[32px]" style={{ color: "#fff" }}>BACKYARD BUILD</h2>
                <p className="font-mono text-[11px] mt-1" style={{ color: "#AAAAAA" }}>Generated in 4 minutes from one photo</p>
                <p className="font-mono text-[10px] mt-4" style={{ color: "#555" }}>↑ See another</p>
              </div>
            </section>

            {/* Section 3 — Video 2 */}
            <section className="relative w-full" style={{ height: "100vh" }}>
              <video src="/videos/transform-2.mp4" autoPlay muted loop playsInline className="absolute inset-0 w-full h-full object-cover" />
              <div className="absolute inset-0" style={{ background: "linear-gradient(to top, rgba(0,0,0,0.9) 0%, transparent 60%)" }} />
              <div className="absolute bottom-0 left-0 right-0 p-6 pb-10">
                <h2 className="font-display font-bold text-[32px]" style={{ color: "#fff" }}>FULL RENOVATION</h2>
                <p className="font-mono text-[11px] mt-1" style={{ color: "#AAAAAA" }}>Generated in 4 minutes from one photo</p>
                <p className="font-mono text-[10px] mt-4" style={{ color: "#555" }}>↑ Get started</p>
              </div>
            </section>

            {/* Section 4 — CTA */}
            <section className="min-h-screen flex flex-col items-center justify-center px-6 text-center" style={{ background: "#E8C547" }}>
              <h2 className="font-display font-bold text-[72px] leading-[0.9] mb-4" style={{ color: "#000" }}>YOUR TURN.</h2>
              <p className="text-[16px] mb-8" style={{ color: "#333" }}>Create your first transformation video.</p>
              <Link
                to="/login?returnUrl=/video?mode=transform"
                className="block w-full py-4 text-center font-display text-[18px] font-bold mb-3"
                style={{ background: "#000", color: "#fff", borderRadius: 0 }}
              >
                CREATE YOUR OWN →
              </Link>
              <Link
                to="/credits"
                className="block w-full py-4 text-center font-display text-[18px] font-bold"
                style={{ background: "transparent", color: "#000", border: "2px solid #000", borderRadius: 0 }}
              >
                SEE PRICING
              </Link>
            </section>
          </>
        ) : (
          /* ═══ DESKTOP LAYOUT ═══ */
          <div className="pt-14">
            {/* Intro */}
            <div className="text-center py-16 px-4">
              <p className="font-mono text-[11px] tracking-[2px] mb-3" style={{ color: "#E8C547" }}>⚡ LIVE DEMO</p>
              <h1 className="font-display font-bold text-[64px] leading-[0.9] mb-4" style={{ color: "#fff" }}>SEE WHAT GETS MADE.</h1>
              <p className="text-[16px] max-w-[480px] mx-auto" style={{ color: "#888" }}>
                Two real transformation videos generated by The Vantage. No editing. No crew. Just one after photo each.
              </p>
            </div>

            {/* Two phones */}
            <div className="flex items-end justify-center gap-12 pb-4">
              <div className="flex flex-col items-center">
                <p className="font-mono text-[10px] tracking-[2px] mb-3" style={{ color: "#E8C547" }}>VIDEO 1</p>
                <PhoneMockup videoSrc="/videos/transform-1.mp4" label="BACKYARD BUILD · 4 CREDITS" />
              </div>
              <div className="flex flex-col items-center">
                <p className="font-mono text-[10px] tracking-[2px] mb-3" style={{ color: "#E8C547" }}>VIDEO 2</p>
                <PhoneMockup videoSrc="/videos/transform-2.mp4" label="FULL RENOVATION · 4 CREDITS" />
              </div>
            </div>

            {/* Conversion panel */}
            <div className="max-w-[600px] mx-auto mt-12 mb-16 p-12 text-center" style={{ background: "#1A1A1A" }}>
              <h2 className="font-display font-bold text-[40px] mb-4" style={{ color: "#fff" }}>WANT VIDEOS LIKE THESE?</h2>
              <div className="flex items-center justify-center gap-6 mb-8">
                {["4 min", "1 photo", "1080p"].map((s, i) => (
                  <span key={i} className="font-mono text-[12px]" style={{ color: "#AAAAAA" }}>{s}</span>
                ))}
              </div>
              <Link
                to="/login?returnUrl=/video?mode=transform"
                className="block w-full py-4 text-center font-display text-[18px] font-bold mb-3"
                style={{ background: "#E8C547", color: "#000", borderRadius: 0 }}
              >
                CREATE YOUR OWN →
              </Link>
              <Link
                to="/credits"
                className="block w-full py-4 text-center font-display text-[18px] font-bold"
                style={{ background: "transparent", color: "#fff", border: "1px solid #333", borderRadius: 0 }}
              >
                SEE PRICING
              </Link>
            </div>
          </div>
        )}

        {/* Floating install button (mobile only) */}
        {isMobile && !isStandalone && (
          <button
            type="button"
            onClick={handleInstallClick}
            className="fixed z-50 font-mono text-[11px] font-bold border-none cursor-pointer"
            style={{
              bottom: 80,
              right: 16,
              background: "#E8C547",
              color: "#0A0A0A",
              padding: "12px 20px",
              borderRadius: 999,
              boxShadow: "0 4px 20px rgba(232,197,71,0.4)",
              animation: "installBounce 2s ease-in-out infinite",
            }}
          >
            📱 Install App
          </button>
        )}

        {/* iOS install modal */}
        {showInstallModal && (
          <div className="fixed inset-0 z-[60] flex items-end justify-center" style={{ background: "rgba(0,0,0,0.6)" }} onClick={() => setShowInstallModal(false)}>
            <div
              className="w-full max-w-md p-6 pb-10 relative"
              style={{ background: "#1A1A1A", borderRadius: "16px 16px 0 0" }}
              onClick={(e) => e.stopPropagation()}
            >
              {/* Handle */}
              <div className="w-10 h-1 rounded-full mx-auto mb-4" style={{ background: "#555" }} />
              <button type="button" onClick={() => setShowInstallModal(false)} className="absolute top-4 right-4 bg-transparent border-none cursor-pointer" style={{ color: "#888" }}>
                <X className="h-5 w-5" />
              </button>
              <h3 className="font-display font-bold text-[28px] mb-6" style={{ color: "#fff" }}>ADD TO HOME SCREEN</h3>
              <div className="flex flex-col gap-4">
                {[
                  { icon: "🧭", text: "Open in Safari" },
                  { icon: "↑", text: "Tap the Share button" },
                  { icon: "+", text: "Tap Add to Home Screen" },
                  { icon: "✓", text: "Tap Add — you're done!" },
                ].map((step, i) => (
                  <div key={i} className="flex items-center gap-3">
                    <div className="flex-shrink-0 flex items-center justify-center font-mono text-[14px] font-bold"
                      style={{ width: 32, height: 32, borderRadius: "50%", background: "#E8C547", color: "#000" }}
                    >
                      {step.icon}
                    </div>
                    <span className="font-mono text-[13px]" style={{ color: "#AAAAAA" }}>{step.text}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      <style>{`
        @keyframes installBounce {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-6px); }
        }
      `}</style>
    </>
  );
};

export default Demo;
