import { Helmet } from "react-helmet-async";
import { Link } from "react-router-dom";
import LuxuryHeader from "@/components/lux/LuxuryHeader";
import LuxuryFooter from "@/components/lux/LuxuryFooter";
import EditorialHero from "@/components/lux/EditorialHero";
import StatStrip from "@/components/lux/StatStrip";
import VideoReel from "@/components/lux/VideoReel";
import BeforeAfterSlider from "@/components/lux/BeforeAfterSlider";
import SectionHeading from "@/components/lux/SectionHeading";
import Marquee from "@/components/lux/Marquee";
import { useCtaNavigation } from "@/hooks/useCtaNavigation";

type Slug =
  | "landscaping"
  | "pool-builders"
  | "kitchen-renovation"
  | "bathroom-renovation"
  | "outdoor-living"
  | "general-construction";

interface Content {
  trade: string;
  edition: string;
  heroTitleA: string;
  heroTitleB: string;
  heroItalic: string;
  heroSub: string;
  metaTitle: string;
  metaDesc: string;
  // The trade page shows ONE before/after slider + ONE autoplay video tile.
  // Both must come from the SAME vantage folder so the assets stay coherent.
  sliderBefore: string;
  sliderAfter: string;
  sliderCaption: string;
  videoSrc: string;
  videoPoster: string;
  videoCaption: string;
  faq: { q: string; a: string }[];
  byline: string;
  heroImage: string;
}

// All imagery is real Vantage customer output — every trade page is bound to
// ONE vantage folder so the before/after pair and the video stay coherent.
const CONTENT: Record<Slug, Content> = {
  "landscaping": {
    trade: "Landscaping",
    edition: "The Landscape Edition",
    heroTitleA: "Bare ground",
    heroTitleB: "to dream yard,",
    heroItalic: "in twelve seconds.",
    heroSub: "One photograph of your finished garden. A cinematic before-and-after film engineered for Reels and TikTok. No before photo required — the studio reconstructs it.",
    metaTitle: "Cinematic Films for Landscapers — The Vantage",
    metaDesc: "Turn your finished garden photos into scroll-stopping transformation films. Built for Australian and US landscapers. 50 free credits, no card.",
    sliderBefore: "/vantage/backyard-slow-reveal/before.jpg",
    sliderAfter: "/vantage/backyard-slow-reveal/input.jpg",
    sliderCaption: "REAL CUSTOMER OUTPUT · LANDSCAPING",
    videoSrc: "/vantage/backyard-slow-reveal/result.mp4",
    videoPoster: "/vantage/backyard-slow-reveal/input.jpg",
    videoCaption: "WATCH THE FILM · GENERATED BY THE STUDIO",
    
    byline: "A LANDSCAPE FILM · LARSEN GARDENS",
    heroImage: "/vantage/backyard-slow-reveal/input.jpg",
    faq: [
      { q: "Do I need a before photo of the garden?", a: "No. Submit your finished after frame — the studio reconstructs an overgrown-or-bare prior state that matches your exact site." },
      { q: "Does it work for hardscape jobs?", a: "Yes. Driveways, retaining walls, paving, turf, and planting beds all transform beautifully." },
      { q: "How fast do I receive the film?", a: "Average render time is 3 minutes 14 seconds. Studio plan subscribers see 90 seconds." },
    ],
  },
  "pool-builders": {
    trade: "Pool Building",
    edition: "The Pool Builder's Edition",
    heroTitleA: "An empty lot",
    heroTitleB: "to a backyard oasis,",
    heroItalic: "in a single frame.",
    heroSub: "One photograph of your finished pool becomes a cinematic reveal worth a $30k+ pipeline. No drone. No second crew. No videographer.",
    metaTitle: "Cinematic Films for Pool Builders — The Vantage",
    metaDesc: "Show the full magnitude of every pool build. One after photo becomes a 1080p transformation film in minutes. 50 free credits to start.",
    sliderBefore: "/vantage/backyard-slow-reveal/before.jpg",
    sliderAfter: "/vantage/backyard-slow-reveal/input.jpg",
    sliderCaption: "REAL CUSTOMER OUTPUT · POOL BUILDERS",
    videoSrc: "/vantage/backyard-slow-reveal/result.mp4",
    videoPoster: "/vantage/backyard-slow-reveal/input.jpg",
    videoCaption: "WATCH THE FILM · GENERATED BY THE STUDIO",
    
    byline: "A POOL FILM · MERIDIAN AQUATICS",
    heroImage: "/vantage/backyard-slow-reveal/input.jpg",
    faq: [
      { q: "Does it show the excavation?", a: "Yes. The studio reconstructs a bare-earth prior state and animates the build sequence between the two frames." },
      { q: "Indoor or infinity pools?", a: "Works for any finished pool with a clear photograph — infinity, plunge, lap, spa, and indoor." },
    ],
  },
  "kitchen-renovation": {
    trade: "Kitchen Renovation",
    edition: "The Renovator's Edition",
    heroTitleA: "Dated to delivered,",
    heroTitleB: "on camera —",
    heroItalic: "from one finished frame.",
    heroSub: "The studio reconstructs the dated prior state of your kitchen renovation from a single completed photograph. Every job becomes a Reels-native film.",
    metaTitle: "Cinematic Films for Kitchen Renovators — The Vantage",
    metaDesc: "Turn your finished kitchen photos into cinematic renovation reveals. No before photo needed. 50 free credits, no subscription.",
    sliderBefore: "/vantage/setup/before.webp",
    sliderAfter: "/vantage/setup/after.jpeg",
    sliderCaption: "REAL CUSTOMER OUTPUT · KITCHEN RENOVATION",
    videoSrc: "/vantage/setup/video.mp4",
    videoPoster: "/vantage/setup/after.jpeg",
    videoCaption: "WATCH THE FILM · GENERATED BY THE STUDIO",
    
    byline: "A RENOVATION FILM · WESTBROOK & CO.",
    heroImage: "/vantage/setup/after.jpeg",
    faq: [
      { q: "Do I need a photo of the old kitchen?", a: "No. The studio reconstructs a plausible dated kitchen from your finished frame." },
      { q: "Will it match the actual cabinetry and layout?", a: "The after photograph anchors the camera angle and footprint. The reconstructed prior state matches the same space, in a deteriorated form." },
    ],
  },
  "bathroom-renovation": {
    trade: "Bathroom Renovation",
    edition: "The Tile & Stone Edition",
    heroTitleA: "The renovation",
    heroTitleB: "no one filmed —",
    heroItalic: "rendered in motion.",
    heroSub: "Show off your tiling, your stonework, your finishings. The studio turns one finished bathroom photograph into a film that closes booking inquiries.",
    metaTitle: "Cinematic Films for Bathroom Renovators — The Vantage",
    metaDesc: "Transform finished bathroom photos into viral renovation films. Built for renovators and tilers. 50 free credits.",
    sliderBefore: "/vantage/cleanup/mo.jpg",
    sliderAfter: "/vantage/cleanup/mo.jpg",
    sliderCaption: "REAL CUSTOMER OUTPUT · BATHROOM RENOVATION",
    videoSrc: "/vantage/cleanup/result.mp4",
    videoPoster: "/vantage/cleanup/mo.jpg",
    videoCaption: "WATCH THE FILM · GENERATED BY THE STUDIO",
    
    byline: "A TILER'S FILM · STILLWATER STUDIO",
    heroImage: "/vantage/cleanup/mo.jpg",
    faq: [
      { q: "Wet rooms and ensuites?", a: "Yes — any finished bathroom with a clear, well-lit photograph works." },
      { q: "Tile-only jobs?", a: "Works beautifully. Regrouting, re-tiling, and waterproofing reveals all supported." },
    ],
  },
  "outdoor-living": {
    trade: "Outdoor Living",
    edition: "The Outdoor Edition",
    heroTitleA: "Decks, pergolas,",
    heroTitleB: "outdoor kitchens —",
    heroItalic: "rendered in motion.",
    heroSub: "One photograph of your finished build becomes a cinematic transformation film, ready for Reels, TikTok, and the algorithm.",
    metaTitle: "Cinematic Films for Outdoor Living Builds — The Vantage",
    metaDesc: "Decks, pergolas, outdoor kitchens, alfresco areas. One after photo, one cinematic film. 50 free credits, no subscription.",
    sliderBefore: "/vantage/backyard-slow-reveal/before.jpg",
    sliderAfter: "/vantage/backyard-slow-reveal/input.jpg",
    sliderCaption: "REAL CUSTOMER OUTPUT · OUTDOOR LIVING",
    videoSrc: "/vantage/backyard-slow-reveal/result.mp4",
    videoPoster: "/vantage/backyard-slow-reveal/input.jpg",
    videoCaption: "WATCH THE FILM · GENERATED BY THE STUDIO",
    
    byline: "AN OUTDOOR FILM · NORTH SHORE",
    heroImage: "/vantage/backyard-slow-reveal/input.jpg",
    faq: [
      { q: "Alfresco and patio builds?", a: "Yes. Decks, pergolas, outdoor kitchens, cabanas, and fire pits — all supported." },
      { q: "Can I post straight to TikTok?", a: "Yes. All outputs are 1080×1920 vertical MP4, ready for TikTok, Reels, and Shorts." },
    ],
  },
  "general-construction": {
    trade: "General Construction",
    edition: "The Builder's Edition",
    heroTitleA: "The build story,",
    heroTitleB: "without filming",
    heroItalic: "the build.",
    heroSub: "For general contractors, builders, and developers. One after photograph per job becomes a Reels-ready film. No videographer required.",
    metaTitle: "Cinematic Films for Builders — The Vantage",
    metaDesc: "For general contractors, builders, and developers. One after photo per job becomes a social-ready transformation film. 50 free credits.",
    sliderBefore: "/vantage/contractor/before.jpg",
    sliderAfter: "/vantage/contractor/before.jpg",
    sliderCaption: "REAL CUSTOMER OUTPUT · GENERAL CONSTRUCTION",
    videoSrc: "/vantage/contractor/result.mp4",
    videoPoster: "/vantage/contractor/before.jpg",
    videoCaption: "WATCH THE FILM · GENERATED BY THE STUDIO",
    
    byline: "A BUILDER'S FILM · ATWOOD CONSTRUCTION",
    heroImage: "/vantage/contractor/before.jpg",
    faq: [
      { q: "Full home builds?", a: "Yes. New builds, knockdown-rebuilds, and full renovations are all supported." },
      { q: "Multiple trades?", a: "Yes. Submit any finished work — landscaping, builds, renovations, fitouts." },
    ],
  },
};

interface Props { slug: Slug; }

const IndustryLanding = ({ slug }: Props) => {
  const c = CONTENT[slug];
  const { destinationFor, isLoggedIn } = useCtaNavigation();
  const cta = destinationFor("create");
  const canonical = `https://thevantage.co/${slug}`;

  return (
    <>
      <Helmet>
        <title>{c.metaTitle}</title>
        <meta name="description" content={c.metaDesc} />
        <meta property="og:title" content={c.metaTitle} />
        <meta property="og:description" content={c.metaDesc} />
        <meta property="og:url" content={canonical} />
        <link rel="canonical" href={canonical} />
      </Helmet>

      <div className="min-h-screen lux-bg-bone" style={{ color: "var(--lux-ink)" }}>
        <LuxuryHeader variant="bone" />

        <main id="main-content">
          <EditorialHero
            eyebrow={`A DOSSIER FOR ${c.trade.toUpperCase()}`}
            edition={c.edition}
            title={
              <>
                {c.heroTitleA}
                <br />
                {c.heroTitleB}
                <br />
                <span className="lux-display-italic" style={{ color: "var(--lux-rust)" }}>{c.heroItalic}</span>
              </>
            }
            subtitle={c.heroSub}
            primaryCta={{ label: isLoggedIn ? "ENTER THE STUDIO →" : "BEGIN FREE — 50 CREDITS →", to: cta }}
            secondaryCta={{ label: "VIEW THE REEL", to: "/gallery" }}
            rightImage={c.heroImage}
            rightVideo="/vantage/contractor/result.mp4"
            byline={c.byline}
          />

          <Marquee
            items={[
              `TRUSTED BY ${c.trade.toUpperCase()} STUDIOS IN  ·  Boston`,
              "Los Angeles",
              "New York",
              "Austin",
              "Chicago",
              "Sydney",
              "Melbourne",
              "London",
            ]}
          />

          <section className="lux-section lux-bg-cream">
            <div className="lux-container">
              <SectionHeading
                eyebrow="THE METAMORPHOSIS"
                title="Drag the seam."
                italic={`See ${c.trade.toLowerCase()} in motion.`}
                align="center"
                className="mb-16"
              />
              <div className="grid md:grid-cols-2 gap-8 md:gap-12">
                <BeforeAfterSlider
                  before={c.sliderBefore}
                  after={c.sliderAfter}
                  afterVideo={c.videoSrc}
                  ratio="4/5"
                  caption={c.sliderCaption}
                />
                <div
                  className="relative overflow-hidden"
                  style={{
                    aspectRatio: "4 / 5",
                    background: "var(--lux-ink)",
                    border: "1px solid var(--lux-hairline)",
                  }}
                >
                  <video
                    src={c.videoSrc}
                    poster={c.videoPoster}
                    autoPlay
                    muted
                    loop
                    playsInline
                    className="absolute inset-0 w-full h-full object-cover"
                  />
                  <div
                    className="absolute top-3 left-3 px-3 py-1.5 lux-eyebrow"
                    style={{
                      background: "rgba(14,14,12,0.7)",
                      color: "var(--lux-bone)",
                      fontSize: "0.6rem",
                      backdropFilter: "blur(8px)",
                    }}
                  >
                    PLAYING
                  </div>
                  <div
                    className="absolute bottom-3 left-3 right-3 lux-eyebrow"
                    style={{
                      color: "var(--lux-bone)",
                      fontSize: "0.65rem",
                      textShadow: "0 1px 8px rgba(0,0,0,0.6)",
                    }}
                  >
                    {c.videoCaption}
                  </div>
                </div>
              </div>
            </div>
          </section>

          <section className="lux-section lux-bg-ink lux-grain" style={{ color: "var(--lux-bone)" }}>
            <div className="lux-container">
              <VideoReel
                eyebrow={`THE ${c.trade.toUpperCase()} REEL · REAL CUSTOMER OUTPUT`}
                title={`Recently delivered to ${c.trade.toLowerCase()} studios.`}
                clips={[
                  { src: "/vantage/ranch-build/result.mp4", label: "The Beacon Project", byline: "ATWOOD · MASS." },
                  { src: "/vantage/backyard-slow-reveal/result.mp4", label: "Olive & 14th", byline: "MERIDIAN · LOS ANGELES" },
                  { src: "/vantage/ranch-clean/video.mp4", label: "Cedar Crest Cleanup", byline: "VANTAGE · NORTHEAST" },
                ]}
              />
            </div>
          </section>

          <section className="lux-section lux-bg-bone">
            <div className="lux-container grid lg:grid-cols-12 gap-12">
              <div className="lg:col-span-4 lg:sticky lg:top-32 lg:self-start">
                <SectionHeading
                  eyebrow="QUIET QUESTIONS"
                  title={`Asked by ${c.trade.toLowerCase()}s.`}
                  italic="Answered, plainly."
                />
              </div>
              <div className="lg:col-span-8">
                {c.faq.map((f, i) => (
                  <details key={i} className="group py-7" style={{ borderBottom: "1px solid var(--lux-hairline)" }}>
                    <summary className="flex items-baseline justify-between cursor-pointer list-none">
                      <span className="lux-display text-2xl md:text-3xl pr-8" style={{ letterSpacing: "-0.012em" }}>{f.q}</span>
                      <span className="lux-display-italic flex-shrink-0 transition-transform group-open:rotate-45" style={{ color: "var(--lux-rust)", fontSize: 32, lineHeight: 1 }}>+</span>
                    </summary>
                    <p className="lux-prose mt-5" style={{ maxWidth: 640 }}>{f.a}</p>
                  </details>
                ))}
              </div>
            </div>
          </section>

          <StatStrip
            variant="cream"
            stats={[
              { value: "3 min", label: "AVG. RENDER" },
              { value: "1080p", label: "VERTICAL · 9:16" },
              { value: "50", label: "FREE CREDITS" },
              { value: "$0", label: "TO BEGIN" },
            ]}
          />

          <section className="lux-section relative overflow-hidden lux-bg-ink lux-grain" style={{ color: "var(--lux-bone)" }}>
            <div className="absolute inset-0 opacity-25" style={{ backgroundImage: `url(${c.heroImage})`, backgroundSize: "cover", backgroundPosition: "center" }} />
            <div className="absolute inset-0" style={{ background: "linear-gradient(to bottom, rgba(14,14,12,0.85), rgba(14,14,12,0.95))" }} />
            <div className="relative lux-container text-center py-32">
              <h2 className="lux-display" style={{ fontSize: "clamp(2.6rem, 6vw, 5.5rem)", lineHeight: 0.95, color: "var(--lux-bone)" }}>
                Begin with one
                <br />
                <span className="lux-display-italic" style={{ color: "var(--lux-champagne)" }}>finished frame.</span>
              </h2>
              <div className="mt-12 flex flex-wrap items-center justify-center gap-6">
                <Link to={cta} className="lux-btn lux-btn-bone">
                  {isLoggedIn ? "ENTER THE STUDIO →" : "BEGIN FREE — 50 CREDITS →"}
                </Link>
              </div>
            </div>
          </section>
        </main>

        <LuxuryFooter />
      </div>
    </>
  );
};

export default IndustryLanding;
